[package]
name = "adventofcode2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
reqwest = "0.12"
tokio = { version = "1.34.0", features = ["full"] }
clap = { version = "4", features = ["derive"] }
