[package]
name = "adventofcode2024"
version = "0.1.0"
edition = "2021"
default-run = "day1"

[dependencies]
anyhow = "1"
reqwest = "0.12"
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
